//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : mis
	/// Data Source    : mis
	/// Server Version : 3.24.0
	/// </summary>
	public partial class MisDB : LinqToDB.Data.DataConnection
	{
		public ITable<Employee> Employees { get { return this.GetTable<Employee>(); } }
		public ITable<Server>   Servers   { get { return this.GetTable<Server>(); } }

		public MisDB()
		{
			InitDataContext();
		}

		public MisDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("employees")]
	public partial class Employee
	{
		[PrimaryKey, NotNull    ] public long   Id        { get; set; } // integer
		[Column,     NotNull    ] public string Name      { get; set; } // text(max)
		[Column,     NotNull    ] public string Team      { get; set; } // text(max)
		[Column,        Nullable] public string Title     { get; set; } // text(max)
		[Column,     NotNull    ] public string PCId      { get; set; } // text(max)
		[Column,     NotNull    ] public string Ip        { get; set; } // text(max)
		[Column,        Nullable] public string Extension { get; set; } // text(max)
	}

	[Table("server")]
	public partial class Server
	{
		[PrimaryKey, NotNull    ] public int    ID       { get; set; } // int
		[Column,        Nullable] public string NAME     { get; set; } // text(max)
		[Column,        Nullable] public string Ip       { get; set; } // text(max)
		[Column,        Nullable] public string Account  { get; set; } // text(max)
		[Column,        Nullable] public string Password { get; set; } // text(max)
		[Column,        Nullable] public string Remark   { get; set; } // text(max)
	}

	public static partial class TableExtensions
	{
		public static Employee Find(this ITable<Employee> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Server Find(this ITable<Server> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
